version: "3.8"

services:
  agro-verx:
    build: .
    command: python agro_verx/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/agro_verx
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
