# Generated by Django 5.0.7 on 2024-08-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreStateModel',
            fields=[
                ('state_id', models.BigAutoField(db_column='state_id', primary_key=True, serialize=False)),
                ('state_name', models.CharField(db_column='state_name', max_length=255, unique=True)),
                ('state_abbreviation', models.CharField(db_column='state_abbreviation', max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'core_state',
            },
        ),
        migrations.CreateModel(
            name='CoreCityModel',
            fields=[
                ('city_id', models.BigAutoField(db_column='city_id', primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city_name', max_length=255)),
                ('state_id', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.corestatemodel')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'core_city',
                'unique_together': {('city_name', 'state_id')},
            },
        ),
    ]
