# Generated by Django 5.0.7 on 2024-08-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                (
                    'producer_id',
                    models.BigAutoField(
                        db_column='producer_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'producer_name',
                    models.CharField(
                        db_column='producer_name', max_length=255
                    ),
                ),
                (
                    'producer_document_type',
                    models.CharField(
                        choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')],
                        db_column='producer_document_type',
                        max_length=4,
                    ),
                ),
                (
                    'producer_cpf_number',
                    models.CharField(
                        db_column='producer_cpf_number',
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    'producer_cnpj_number',
                    models.CharField(
                        db_column='producer_cnpj_number',
                        max_length=18,
                        null=True,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, db_column='created_at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, db_column='updated_at'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'db_table': 'producer_producer',
            },
        ),
        migrations.CreateModel(
            name='ProducerPlantationTypeModel',
            fields=[
                (
                    'plantation_type_id',
                    models.BigAutoField(
                        db_column='plantation_type_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'plantation_type',
                    models.CharField(
                        db_column='plantation_type', max_length=50, unique=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'Plantation Type',
                'verbose_name_plural': 'Plantation Types',
                'db_table': 'producer_plantation_type',
            },
        ),
        migrations.CreateModel(
            name='ProducerFarmModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'farm_name',
                    models.CharField(db_column='farm_name', max_length=128),
                ),
                (
                    'total_area_hectares',
                    models.DecimalField(
                        db_column='total_area_hectares',
                        decimal_places=2,
                        max_digits=10,
                    ),
                ),
                (
                    'arable_area_hectares',
                    models.DecimalField(
                        db_column='arable_area_hectares',
                        decimal_places=2,
                        max_digits=10,
                    ),
                ),
                (
                    'vegetation_area_hectares',
                    models.DecimalField(
                        db_column='vegetation_area',
                        decimal_places=2,
                        max_digits=10,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, db_column='created_at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, db_column='updated_at'
                    ),
                ),
                (
                    'city_id',
                    models.ForeignKey(
                        db_column='city_id',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='farms',
                        to='core.corecitymodel',
                    ),
                ),
                (
                    'producer_id',
                    models.ForeignKey(
                        db_column='producer_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='farms',
                        to='producer.producermodel',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'db_table': 'producer_farm',
            },
        ),
        migrations.CreateModel(
            name='ProducerFarmPlantationModel',
            fields=[
                (
                    'farm_plantation_id',
                    models.BigAutoField(
                        db_column='farm_plantation_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column='farm_plantation_created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, db_column='farm_plantation_updated_at'
                    ),
                ),
                (
                    'farm_id',
                    models.ForeignKey(
                        db_column='farm_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='farms',
                        to='producer.producerfarmmodel',
                    ),
                ),
                (
                    'plantation_type_id',
                    models.ForeignKey(
                        db_column='plantation_type_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='plantation_types',
                        to='producer.producerplantationtypemodel',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Farm Plantations Types',
                'verbose_name_plural': 'Farm Plantation Type',
                'db_table': 'producer_farm_plantation_type',
            },
        ),
        migrations.AddField(
            model_name='producerfarmmodel',
            name='plantations',
            field=models.ManyToManyField(
                through='producer.ProducerFarmPlantationModel',
                to='producer.producerplantationtypemodel',
            ),
        ),
    ]
