# Generated by Django 5.0.7 on 2024-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producermodel',
            name='producer_document_number',
        ),
        migrations.AddField(
            model_name='producermodel',
            name='producer_cnpj_number',
            field=models.CharField(
                db_column='producer_cnpj_number', max_length=18, null=True
            ),
        ),
        migrations.AddField(
            model_name='producermodel',
            name='producer_cpf_number',
            field=models.CharField(
                db_column='producer_cpf_number', max_length=14, null=True
            ),
        ),
    ]
