# Generated by Django 5.0.7 on 2024-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerfarmmodel',
            name='vegetation_area_hectares',
            field=models.DecimalField(
                db_column='vegetation_area_hectares',
                decimal_places=2,
                max_digits=10,
            ),
        ),
    ]
