# Generated by Django 5.0.7 on 2024-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'producer',
            '0002_remove_producermodel_producer_document_number_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='producermodel',
            name='arable_area_hectares',
            field=models.DecimalField(
                db_column='arable_area_hectares',
                decimal_places=2,
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='total_area_hectares',
            field=models.DecimalField(
                db_column='total_area_hectares',
                decimal_places=2,
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='vegetation_area_hectares',
            field=models.DecimalField(
                db_column='vegetation_area', decimal_places=2, max_digits=10
            ),
        ),
    ]
